### ISSUE TITLE
PacketReader causes crash because of a slice out of bounds error

### ISSUE THREAD

**Issue by LethalEthan** [LethalEthan/HoneyGO#1]
The reason I'm opening this issue is because the error happened on a public test server I had created, I also want to document my reasoning and possible fixes I implement, it panicked due to:

`panic: runtime error: slice bounds out of range [:45] with capacity 2

goroutine 37 [running]:
Packet.(*PacketReader).ReadString(0xc000061f78, 0xc000000000, 0x0, 0x0, 0x246)
	/home/ethan/Documents/CodeProjects/Go/HoneyGO/src/Packet/PacketReader.go:234 +0x23c
Packet.HandshakePacketCreate(0xc000000002, 0xc000061f78, 0x2, 0x2, 0x0)
	/home/ethan/Documents/CodeProjects/Go/HoneyGO/src/Packet/PacketHandshake.go:22 +0x7c
server.HandleConnection(0xc00030ef00)
	/home/ethan/Documents/CodeProjects/Go/HoneyGO/src/server/Server.go:155 +0x2d9
created by main.main
	/home/ethan/Documents/CodeProjects/Go/HoneyGO/main.go:94 +0x915
`
Just before the panic a handshake was initiated and the CCH (ClientConnectionHandler) was initiated. It shows that there was an issue with reading a string from the packet which is the server address in the Handshake packet.
Possible fixes:

- [x] Check that the stringSize and seek doesn't go past pr.end
- [x] Do a simple handshake packet size check that drops it if it's too low (not ideal)
- [ ] Scrap the old packet read/write system and redesign a new one with support for interfaces

**Comment by LethalEthan** [comment]
I have implemented the first possible fix but I am also considering doing the third one later along the line when complexity increases.
